### ISSUE TITLE
Version for TYPO3 Solr 3.1.0

### ISSUE THREAD

**Issue by lorenzulrich** [obi12341/solr-typo3#3]
A new version of EXT:solr was released requiring Solr 4.10. Are you also in need of it and will you update your container?

**Comment by obi12341** [comment]
yeah will take a look into it this weekend :+1:

**Comment by lorenzulrich** [comment]
Thanks, looking forward!

**Comment by obi12341** [comment]
Finished it. Maybe you want to test it. Working here.

**Comment by lorenzulrich** [comment]
Works just fine, thanks for your work!
