### ISSUE TITLE
[FEATURE] Update the package to support EXT:solr 6.0.0

### ISSUE THREAD

**Issue by manmath** [obi12341/solr-typo3#4]
Extension solr now has released new version 6.0.0. It is really nice to update this docker image to support against that new release (https://typo3.org/extensions/repository/view/solr).

**Comment by obi12341** [comment]
Hey,
thanks for your message. There is now a official Docker Image from typo3-ext/solr. https://hub.docker.com/r/typo3solr/ext-solr/
Maybe you want to try this out. :)
